#!/bin/sh
set -eu
ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src/universal-openwrt"
MOD="$ROOT/modules/service-modules.sh"
UI="$ROOT/luci-app-universal-openwrt/htdocs/luci-static/resources/view/universal-openwrt/overview.js"
RPC="$ROOT/luci-app-universal-openwrt/root/usr/share/rpcd/ucode/luci.universal_openwrt"
ACL="$ROOT/luci-app-universal-openwrt/root/usr/share/rpcd/acl.d/luci-app-universal-openwrt.json"

grep -q 'SERVICE_MODULE_STATE_DIR=' "$SRC"
grep -q 'service_module_queue_build' "$SRC"
grep -q 'service_module_health_calc' "$SRC"
grep -q 'service_module_record' "$SRC"
grep -q 'service_group_quality' "$SRC"
grep -q 'consecutive_failures' "$SRC"
grep -q 'cooldown_until' "$SRC"
grep -q 'protected-module-regression' "$SRC"
grep -q 'service_module_for_group' "$SRC"
grep -q 'GM="$(service_module_for_group "$G")"' "$SRC"
grep -q 'service-improved-stable' "$SRC"
grep -q 'service_strategy_available' "$SRC"
grep -q 'service_strategy_rank' "$SRC"
grep -q 'now < last+cd' "$SRC"
grep -q 'QSTAB" -ge 75' "$SRC"
grep -q '\[ "$STAT" = OK \]' "$SRC"
grep -q 'SERVICE_MODULES=.*news' "$MOD"
grep -q "news) echo 'Новости'" "$MOD"
grep -q 'ai) \[ "$DG" = ai \] || \[ "$DG" = openai \]' "$SRC"
grep -q 'social) \[ "$DG" = social \] || \[ "$DG" = tiktok \]' "$SRC"
grep -q 'VPN_MONITOR_LOCK=.*\.d' "$SRC"
grep -q 'PRED_LOCK=.*predictive.lock' "$SRC"
grep -q 'PRED_LOCK}.d' "$SRC"
grep -q 'telegram_controller_lock' "$ROOT/modules/telegram-controller.sh"
grep -q 'QSTAB' "$SRC"
grep -q -- '--service-modules-health' "$SRC"
grep -q -- '--service-modules-queues' "$SRC"
grep -q 'SERVICE_MODULES=' "$MOD"
grep -q 'service_modules_health' "$RPC"
grep -q 'service_modules_queues' "$RPC"
grep -q 'service_modules_health' "$ACL"
grep -q 'uowrt-module-health' "$UI"
sh -n "$SRC"
sh -n "$MOD"
node --check "$UI"
printf '%s\n' 'SERVICE_MODULE_LEARNING=PASS'
