#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1
NAME=universal-openwrt-vpn-monitor
BIN=/usr/sbin/universal-openwrt

autostart(){ [ -f /etc/universal-openwrt/monitor.conf ] && grep -q '^enabled=1$' /etc/universal-openwrt/monitor.conf; }
start_service(){
  autostart || return 0
  procd_open_instance
  procd_set_param command /bin/sh -c "while :; do $BIN --vpn-monitor-run; S=900; [ -f /etc/universal-openwrt/monitor.conf ] && S=\$(awk -F= '\$1==\"interval\"{print \$2}' /etc/universal-openwrt/monitor.conf); case \"\$S\" in ''|*[!0-9]*) S=900;; esac; sleep \"\$S\"; done"
  procd_set_param respawn 3600 5 5
  procd_close_instance
}
