#!/bin/sh /etc/rc.common
START=95
STOP=10
USE_PROCD=1

APP=/usr/sbin/universal-openwrt

start_service() {
    [ -x "$APP" ] || return 0
    procd_open_instance
    procd_set_param command "$APP" --vpn-monitor-run
    procd_set_param respawn 3600 5 1
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
